backend:
  name: github
  repo: seungha-kim/cms-test
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/photos.json"
        label: "Photos"
        name: "photos"
        fields:
          - label: Photos
            name: photos
            widget: list
            fields:
              - label: Thumbnail
                name: thumbnail
                widget: image
              - label: Original Image
                name: originalImage
                widget: image
              - label: Description
                name: description
                widget: text